### ISSUE TITLE
what does `Fake AFK` do?

### ISSUE THREAD

**Issue by LastExceed** [AjisaiMirai/plugins#1]
edit - update for anyone else wondering: i've decompiled the plugin dll and turns out it does nothing at all. the value gets saved to the plugin configuration but isn't referenced anywhere other than the checkbox in the gui

still, thank you AjisaiMirai for this plugin, the quickleave feature was very useful for spamming ifrit for my ARR relic weapon

**Comment by AjisaiMirai** [comment]
Very late reply, kinda forgot about it.

Fake-AFK was a feature where it would change the internal timer in such a way, you could move around and still have the AFK symbol as your sign. This was later removed when SE stopped using the function.
