### ISSUE TITLE
Who emoted at me

### ISSUE THREAD

**Issue by clytemnestra** [AjisaiMirai/plugins#2]
Hello Aji, I wanted to ask if you can make WEAM to show only the overlay without the config panel, or add a command to do so, similar to peeping tom. Thank you.

**Comment by AjisaiMirai** [comment]
The option "Show Overlay" should be able to draw without having the configuration window open.
But I can add a command to open this overlay from the chat.

**Comment by AjisaiMirai** [comment]
> Works wonderful, thank you very much ♥

Config command didn't work, it now does on ver 0.2.15.2. All should work as intented
