### ISSUE TITLE
Duplicated emotes from the same person

### ISSUE THREAD

**Issue by clytemnestra** [AjisaiMirai/plugins#3]
Hello, if the same person uses the same emote it would be nice to have a setting to register duplicates with (n) like chat2 has:

![image](https://user-images.githubusercontent.com/7060048/192121479-592e3a4e-02da-473d-825a-8d48695594a2.png)

That way if you're getting spammed by someone, you can still see previous emotes that would get deleted otherwise.

**Comment by AjisaiMirai** [comment]
Added functionality.
![image](https://user-images.githubusercontent.com/101881598/200121636-3a3217df-8228-4422-b114-2b6a6dc1a24c.png)

**Comment by AjisaiMirai** [comment]
> Works wonderful, thank you so much ❤️
> 
> I don't really understand these others configs ![image](https://user-images.githubusercontent.com/7060048/200185307-99b15c51-f129-4364-a4e2-4389604dc0c3.png) beesknees, macro, overseer, stalkee, custom notifs

Beesknees: sends a chatlog only visible to you who used beesknees. Left over artifact but still somewhat funny to poke people with. 

Macro: Essentially sends a “PAGE_UP” keystroke to the game window whenever someone would do /pet when targeting you. You can bind a “/em” to page up to react on every pet doing done to you. Has a cooldown. 

Overseer: Disables logging of people in your stalkee list. 

Stalkee: List of people you want to track emotes of. 

Custom Notifs: I never knew I could interact with Dalamud’s api to render an DirectX notification. This is just a very basic implementation to render my own notifications. Runs in occurrence with the main emote log list.

**Comment by AjisaiMirai** [comment]
Correct!
It logs emotes being done to the user and logs their outgoing emotes. 

“Ignore self” should remove yourself from appearing when doing emotes to your friend. 

> hmm I think the stalkee thing doesn't work, or works in reverse?
> ![image](https://user-images.githubusercontent.com/7060048/200333227-3067d45b-fde0-48f4-ab66-c915fac5da96.png)
> I added a friend and that log is me doing the emote to them, but if they do it to me it looks normal:
> ![image](https://user-images.githubusercontent.com/7060048/200334320-dc22b377-88b6-40f3-95e7-73407d53df0a.png)
> Maybe I misunderstand
