### ISSUE TITLE
WEAM - broke

### ISSUE THREAD

**Issue by clytemnestra** [AjisaiMirai/plugins#5]
Hello there,

Who emoted at me is broken again after patch:

![image](https://user-images.githubusercontent.com/7060048/202140428-94539612-5515-4fa4-8d39-72adcaf6b4a9.png)

**Comment by AjisaiMirai** [comment]
Please restart. This is the sole reason I moved from signatures. For some reason when I hook a function once and it updates, the hook never disposes/unhooks. Making the signature invalid. A restart of the game solves this.

**Comment by AjisaiMirai** [comment]
Very odd. Played after patch and seemed to work for me and a friend. Will check when I’m able.

**Comment by AjisaiMirai** [comment]
> I did, however I get the error on the login screen as well:
> 
> ![image](https://user-images.githubusercontent.com/7060048/202142044-32c61ade-22f5-493d-8d7c-ff3a685066b9.png)
> 
> Been getting it since yesterday after patch.

Do you by chance have another plugin which revolves around incoming emotes? E.G. PatMe?

**Comment by AjisaiMirai** [comment]
> I do, I use them both.

I’ll ass a fallback then, both uses the same function so if PatMe hooks it first WEAM fails.

**Comment by AjisaiMirai** [comment]
If signature won't work, offset is being used again. Should hook fine. If the UI doesn't show run the command to show it again.
